Repository BotLino/Lino, pull requests merged in 2019-05, with the labels that each got.

#35 Configuração do Code Climate
  .codeclimate.yml
  README.md
Labels: code quality, new feature

#40 Add UnB Idiomas new interview to docs
  docs/interviews/interviews.md
Labels: GCES

#38 Updates the master with importants modifications
  .codeclimate.yml
  Dockerfile
  README.md
  docker-compose.yml
  docker/Actions.Dockerfile
  docker/Messenger.Dockerfile
  docker/Telegram.Dockerfile
  docker/actions.requirements.txt
  docs/interviews/interviews.md
  rasa/Makefile
  rasa/actions/buttons_notification.py
  rasa/actions/calendar.py
  rasa/actions/course_period_proof.py
  rasa/actions/daily_breakfast.py
  rasa/actions/daily_dinner.py
  rasa/actions/daily_lunch.py
  rasa/actions/daily_menu.py
  rasa/actions/register_notification.py
  rasa/actions/register_proof.py
  rasa/actions/regular_proof.py
  rasa/actions/schedule.py
  rasa/actions/school_history_proof.py
  rasa/actions/see_notifications.py
  rasa/actions/start.py
  rasa/actions/trigger_notification.py
  rasa/actions/tutoring_proof.py
  rasa/actions/unregister_notification.py
  rasa/actions/week_menu.py
  rasa/credentials.yml
  rasa/data/intents/calendar.md
  rasa/data/intents/compliments.md
  rasa/data/intents/documents.md
  rasa/data/intents/general.md
  rasa/data/intents/menu.md
  rasa/data/intents/notifications.md
  rasa/data/intents/random.md
  rasa/data/stories/main.md
  rasa/domain.yml
  rasa/endpoints.yml
  rasa/images/CoursePeriodProof/step1.png
  rasa/images/CoursePeriodProof/step2.png
  rasa/images/CoursePeriodProof/step3.png
  rasa/images/CoursePeriodProof/step4.png
  rasa/images/CoursePeriodProof/step5.png
  rasa/images/SchoolHistoryProof/step1.png
  rasa/images/SchoolHistoryProof/step2.png
  rasa/images/SchoolHistoryProof/step3.png
  rasa/images/SchoolHistoryProof/step4.png
  rasa/images/SchoolHistoryProof/step5.png
  rasa/images/TutoringProof/step1.png
  rasa/images/TutoringProof/step2.png
  rasa/images/TutoringProof/step3.png
  rasa/images/TutoringProof/step4.png
  rasa/images/TutoringProof/step5.png
  rasa/policy_config.yml
  rasa/train-messenger.py
  rasa/train-telegram.py
  rasa/train.py
  requirements.txt
  scripts/setup_envs.py
Labels: enhancement
